'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function col(n){let s='';for(;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;}
const X={utils:{},last:null};X.utils.book_new=()=>({SheetNames:[],Sheets:{}});
X.utils.aoa_to_sheet=a=>{const s={};X.utils.sheet_add_aoa(s,a,{origin:'A1'});return s;};
X.utils.sheet_add_aoa=(s,a,{origin})=>{const [,cc,rr]=origin.match(/^([A-Z]+)(\d+)$/);let c=0;for(const z of cc)c=c*26+z.charCodeAt(0)-64;a.forEach((row,i)=>row.forEach((v,j)=>{if(v!=null)s[col(c+j)+(Number(rr)+i)]={t:typeof v==='number'?'n':'s',v};}));};
X.utils.book_append_sheet=(b,s,n)=>{b.SheetNames.push(n);b.Sheets[n]=s;};X.writeFile=(b,n)=>X.last={b,n};
const old={buildHtml:()=> 'LEGACY-UNCHANGED',excel:()=> 'OLD-XLSX',open:()=> 'OLD-OPEN',download:()=> 'OLD-HTML'};
const ctx={window:{GonClientDocument:old,XLSX:X},console,Blob,URL,setTimeout};vm.createContext(ctx);vm.runInContext(fs.readFileSync(process.argv[2],'utf8'),ctx);const P=ctx.window.GonClientDocument;
const legal={legal_name:'Cliente ESEMPIO Srl',address:'Via Esempio 10',postcode:'25000',city:'Comune esempio',province:'BS',country:'IT',vat_number:'00000000000',tax_code:'00000000000',pec:'esempio@example.invalid',sdi_code:'0000000',email:'esempio@example.invalid',phone:'000000',contact:'Referente dimostrativo',payment_terms:'Condizioni dimostrative'};
const fixture={id:'qa-proforma',state:'draft',number:null,revision:0,document:{proforma_schema:3,client:{name:'Cliente ESEMPIO',legal,site:'Cantiere A',sites:[{site:'Cantiere A'}]},header:{issuer:'GON srl - ESEMPIO',summary:'Dati fittizi per verifica del modello',contact:'Referente di prova'},period_from:'2026-09-01',period_to:'2026-09-30',cassa_rate:5,cassa_on_expenses:true,vat_rate:22,discount_percent:0,expenses:[],activities:[{id:'A',ref:1,date:'2026-09-15',site:'Cantiere A',client:'Sede A',employee:'Tecnico Alfa',macro:'Rilievo in campo',type:'Cantiere',description:'Rilievo quote e capisaldi',hours:4},{id:'B',ref:2,date:'2026-09-15',site:'Cantiere A',client:'Sede A',employee:'Tecnico Beta',macro:'Rilievo in campo',type:'Cantiere',description:'Rilievo quote e capisaldi',hours:4}],lines:[{id:'T',mode:'fixed',dates:['2026-09-15'],description:'Rilievo quote e capisaldi - 2 tecnici mezza giornata',site:'Cantiere A',macro:'Rilievo in campo',type:'Cantiere',unit:'intervento',quantity:1,price:450,amount:450,entry_ids:['A','B']}],totals:{services:450,discount:0,expenses:0,net:450,cassa_base:450,cassa:22.5,taxable:472.5,vat:103.95,gross:576.45}}};
const checks=[];function test(name,fn){fn();checks.push(name);}
const before=JSON.stringify(fixture),html=P.buildHtml(fixture),wb=P.workbookV3(fixture);
test('Proforma title and non-fiscal disclaimer',()=>{assert.ok(html.includes('FATTURA PROFORMA'));assert.ok(html.includes('Documento non valido ai fini fiscali'));});
test('Date and performed activity appear in economic and daily tables',()=>{assert.ok((html.match(/15\/09\/2026/g)||[]).length>=3);assert.ok(html.includes('Rilievo quote e capisaldi'));});
test('Customer identity address VAT and PEC are shown',()=>{for(const x of ['Cliente ESEMPIO Srl','Via Esempio 10','00000000000','esempio@example.invalid'])assert.ok(html.includes(x));});
test('Cassa precedes VAT with saved correct amounts',()=>{assert.ok(html.includes('22,50'));assert.ok(html.includes('472,50'));assert.ok(html.includes('103,95'));assert.ok(html.includes('576,45'));});
test('Two original operator records retained for a single charge',()=>{assert.ok(html.includes('Tecnico Alfa'));assert.ok(html.includes('Tecnico Beta'));assert.equal(wb.Sheets.Valorizzazione.F5.v,1);assert.equal(wb.Sheets.Valorizzazione.I5.v,450);});
test('No mutation of source snapshot',()=>assert.equal(JSON.stringify(fixture),before));
test('Workbook Cassa taxable VAT gross and formulas agree',()=>{assert.equal(wb.Sheets.Sintesi.B9.v,22.5);assert.equal(wb.Sheets.Sintesi.B10.v,472.5);assert.equal(wb.Sheets.Sintesi.B11.v,103.95);assert.equal(wb.Sheets.Sintesi.B12.v,576.45);assert.match(wb.Sheets.Sintesi.B12.f,/Valorizzazione/);});
test('Workbook daily dates and operator labels preserved',()=>{assert.equal(wb.Sheets.Attivita.A5.v,'15/09/2026');assert.equal(wb.Sheets.Attivita.C6.v,'Tecnico Beta');});
test('Saved filenames identify a proforma',()=>{P.excel(fixture);assert.match(X.last.n,/^Fattura_proforma_.*\.xlsx$/);});
test('Legacy output delegated without relabelling',()=>{const r=structuredClone(fixture);delete r.document.proforma_schema;assert.equal(P.buildHtml(r),'LEGACY-UNCHANGED');assert.equal(P.excel(r),'OLD-XLSX');});
test('Customer strings and formulas stay escaped text',()=>{const r=structuredClone(fixture);r.document.client.legal.legal_name='<img src=x onerror=1>';r.document.lines[0].description='=1+1';assert.ok(!P.buildHtml(r).includes('<img src=x'));const cell=P.workbookV3(r).Sheets.Valorizzazione.C5;assert.equal(cell.t,'s');assert.ok(!cell.f);});
test('Unknown prices never become a zero total',()=>{const r=structuredClone(fixture);Object.assign(r.document.totals,{net:null,cassa:null,taxable:null,vat:null,gross:null});r.document.lines[0].price=null;r.document.lines[0].amount=null;assert.equal(P.workbookV3(r).Sheets.Sintesi.B12.v,'Da definire');});
test('Empty activity list supports a monthly fee',()=>{const r=structuredClone(fixture);r.document.activities=[];r.document.lines[0].mode='monthly';r.document.lines[0].unit_key='CLIENT_MONTH:2026-09';r.document.lines[0].dates=[];assert.ok(P.buildHtml(r).includes('01/09/2026 - 30/09/2026'));assert.ok(!JSON.stringify(P.workbookV3(r)).includes('I5:I4'));});
if(process.argv[3]){const ui=fs.readFileSync(process.argv[3],'utf8');test('Generated administration keeps proforma controls without customer editor',()=>{for(const token of ['gon_proforma_v3','gvCassa','gvMacroForm','v3ApplyTeam','gvUpgrade','v3PartyComplete','gvRefreshParty'])assert.ok(ui.includes(token),token);for(const token of ['gvProfileForm','gvEditParty','Anagrafica completa cliente'])assert.ok(!ui.includes(token),token);});}
if(process.argv[4]){const reg=fs.readFileSync(process.argv[4],'utf8');test('Customer registry owns complete client master data',()=>{for(const token of ['gon_customer_registry','crMain','cr_vat_number','cr_tax_code','crAddSite','crCassa','data-edit','data-delete'])assert.ok(reg.includes(token),token);});}
if(process.env.GON_TEST_OUTPUT){const out=process.env.GON_TEST_OUTPUT;fs.mkdirSync(out,{recursive:true});fs.writeFileSync(out+'/proforma-v3.html',html);fs.writeFileSync(out+'/proforma-v3-model.json',JSON.stringify(wb));fs.writeFileSync(out+'/fixture.json',JSON.stringify(fixture));}
console.log('PROFORMA V3 TESTS: '+checks.length+' passed: '+checks.join('; '));
